runtime: python39

env_variables:
  SECRET_KEY: 'change-this-to-a-random-secret-key-in-production'
  DATABASE_URL: 'sqlite:///estoque.db'

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /.*
  script: auto

login: required

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.6
